import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    // Add console log to check if translations are loading
    'debug.language': 'Polski',
    // Navigation
    'nav.properties': 'NIERUCHOMOŚCI',
    'nav.transaction': 'TRANSAKCJA',
    'nav.location': 'LOKALIZACJA',
    'nav.investment': 'INWESTYCJA',
    'nav.services': 'USŁUGI',
    
    // Hero Section
    'hero.badge': 'APARTAMENT NA SPRZEDAŻ',
    'hero.title.krakow': 'KRAKÓW',
    'hero.title.stare_miasto': 'STARE MIASTO',
    'hero.title.rynek_glowny': 'RYNEK GŁÓWNY',
    'hero.cta': 'ZOBACZ OFERTY',
    'hero.scroll': 'ZNAJDŹ NIERUCHOMOŚĆ',
    
    // Properties Page
    'properties.title': 'NIERUCHOMOŚCI W',
    'properties.title.krakow': 'KRAKOWIE',
    'properties.search': 'SZUKAJ',
    'properties.details': 'ZOBACZ SZCZEGÓŁY',
    'properties.load_more': 'ZAŁADUJ WIĘCEJ',
    
    // Properties Categories
    'properties.categories.sale': 'SPRZEDAŻ',
    'properties.categories.rent': 'WYNAJEM',
    'properties.categories.off_market': 'OFF MARKET',
    'properties.categories.deluxe': 'DELUXE ESTATES',
    'properties.category.sale.title': 'NIERUCHOMOŚCI',
    'properties.category.sale.subtitle': 'NA SPRZEDAŻ',
    'properties.category.rent.title': 'NIERUCHOMOŚCI',
    'properties.category.rent.subtitle': 'DO WYNAJĘCIA',
    'properties.category.off_market.title': 'OFERTY',
    'properties.category.off_market.subtitle': 'OFF MARKET',
    'properties.category.deluxe.title': 'DELUXE',
    'properties.category.deluxe.subtitle': 'ESTATES',
    
    // Transaction Page
    'transaction.title': 'PROCES',
    'transaction.title.transaction': 'TRANSAKCJI',
    'transaction.start': 'ROZPOCZNIJ PROCES',
    'transaction.consultation': 'UMÓW KONSULTACJĘ',
    'transaction.free_valuation': 'BEZPŁATNA WYCENA',
    'transaction.schedule_meeting': 'UMÓW SPOTKANIE',
    
    // Location Page
    'location.title': 'LOKALIZACJE W',
    'location.title.krakow': 'KRAKOWIE',
    'location.why': 'DLACZEGO',
    'location.why.krakow': 'KRAKÓW?',
    'location.popular': 'POPULARNE',
    'location.popular.districts': 'DZIELNICE',
    'location.potential': 'POTENCJAŁ',
    'location.potential.investment': 'INWESTYCYJNY',
    'location.analysis': 'ANALIZA INWESTYCYJNA',
    
    // Investment Page
    'investment.title': 'INWESTYCJE',
    'investment.title.properties': 'NIERUCHOMOŚCI',
    'investment.types': 'RODZAJE',
    'investment.types.investments': 'INWESTYCJI',
    'investment.suggested': 'SUGEROWANE',
    'investment.suggested.portfolios': 'PORTFELE',
    'investment.calculator': 'KALKULATOR',
    'investment.calculator.investment': 'INWESTYCJI',
    
    // Services Page
    'services.title': 'NASZE',
    'services.title.services': 'USŁUGI',
    'services.main': 'GŁÓWNE',
    'services.main.services': 'USŁUGI',
    'services.additional': 'USŁUGI',
    'services.additional.services': 'DODATKOWE',
    'services.how': 'JAK',
    'services.how.we_work': 'PRACUJEMY?',
    'services.support': 'WSPARCIE',
    'services.support.24_7': '24/7',
    
    // Footer
    'footer.services': 'Usługi',
    'footer.contact': 'Kontakt',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'ZAPISZ SIĘ',
    'footer.rights': '© 2024 Partners International. Wszystkie prawa zastrzeżone.',
    'footer.privacy': 'Polityka prywatności',
    'footer.terms': 'Regulamin',
    'footer.cookies': 'Cookies',
    
    // Contact Dialog
    'contact.title': 'Kontakt',
    'contact.phone': 'Zadzwoń do nas',
    'contact.name': 'Imię',
    'contact.name.placeholder': 'Twoje imię',
    'contact.email': 'Email',
    'contact.email.placeholder': 'twoj@email.pl',
    'contact.message': 'Wiadomość',
    'contact.message.placeholder': 'Treść wiadomości...',
    'contact.send': 'Wyślij',
    
    // Footer Services
    'footer.service.sales': 'Sprzedaż nieruchomości',
    'footer.service.rental': 'Wynajem mieszkań',
    'footer.service.investment': 'Inwestycje zagraniczne',
    'footer.service.legal': 'Doradztwo prawne',
    'footer.service.valuation': 'Wycena nieruchomości',
    'footer.newsletter.placeholder': 'Twój adres email',
    'footer.newsletter.description': 'Otrzymuj najnowsze oferty luksusowych nieruchomości bezpośrednio do swojej skrzynki mailowej.',
    
    // Search and filters
    'search.location.placeholder': 'Lokalizacja, typ nieruchomości...',
    'search.price.range': 'Zakres cenowy',
    'search.price.up_to_1m': 'Do 1,000,000 PLN',
    'search.price.1m_to_2m': '1-2 mln PLN',
    'search.price.2m_to_3m': '2-3 mln PLN',
    'search.price.over_3m': 'Powyżej 3 mln PLN',
    'search.property.type': 'Typ nieruchomości',
    'search.property.apartment': 'Apartament',
    'search.property.house': 'Dom',
    'search.property.penthouse': 'Penthouse',
    'search.property.loft': 'Loft',
    'search.sort': 'Sortuj według',
    'search.sort.price_asc': 'Cena: od najniższej',
    'search.sort.price_desc': 'Cena: od najwyższej',
    'search.sort.area_asc': 'Powierzchnia: od najmniejszej',
    'search.sort.area_desc': 'Powierzchnia: od największej',
    'search.found': 'Znaleziono',
    'search.properties': 'nieruchomości',
    
    // Investment page - additional translations
    'button.analyze_portfolio': 'ANALIZA PORTFELA',
    'button.learn_more': 'DOWIEDZ SIĘ WIĘCEJ',
    'button.choose_portfolio': 'WYBIERZ PORTFEL',
    'button.run_calculator': 'URUCHOM KALKULATOR',
    'button.view_all_offers': 'ZOBACZ WSZYSTKIE OFERTY',
    'button.load_more': 'ZAŁADUJ WIĘCEJ',
    
    // Transaction Page
    'transaction.hero.title': 'PROCES',
    'transaction.hero.title.span': 'TRANSAKCJI', 
    'transaction.hero.description': 'Kompleksowa obsługa sprzedaży i zakupu nieruchomości w Krakowie. Zapewniamy bezpieczne i profesjonalne przeprowadzenie każdej transakcji.',
    'transaction.hero.button': 'ROZPOCZNIJ PROCES',
    'transaction.process.title': 'JAK WYGLĄDA PROCES?',
    'transaction.process.subtitle': 'Nasz sprawdzony proces gwarantuje bezpieczną i skuteczną realizację transakcji',
    'transaction.step1.title': 'PIERWSZA KONSULTACJA',
    'transaction.step1.description': 'Rozpoczynamy od szczegółowej rozmowy o Twoich potrzebach i oczekiwaniach. Analizujemy Twój budżet, preferencje lokalizacyjne oraz cele inwestycyjne.',
    'transaction.step2.title': 'ANALIZA DOKUMENTÓW',
    'transaction.step2.description': 'Sprawdzamy wszystkie dokumenty prawne i finansowe związane z nieruchomością. Weryfikujemy stan prawny, obciążenia oraz możliwe ryzyka prawne.',
    'transaction.step3.title': 'NEGOCJACJE I ZABEZPIECZENIA',
    'transaction.step3.description': 'Prowadzimy profesjonalne negocjacje cenowe i warunków transakcji. Zabezpieczamy Twoje interesy poprzez odpowiednie klauzule umowne.',
    'transaction.step4.title': 'FINALIZACJA TRANSAKCJI',
    'transaction.step4.description': 'Doprowadzamy transakcję do końca z pełnym wsparciem prawnym i logistycznym. Przekazanie kluczy i wszystkich niezbędnych dokumentów.',
    'transaction.services.title': 'USŁUGI W CENIE',
    'transaction.services.title.span': 'TRANSAKCJI',
    'transaction.services.description': 'Nasze kompleksowe usługi obejmują wszystkie aspekty transakcji nieruchomości. Nie musisz martwić się o szczegóły - my zajmiemy się wszystkim.',
    'transaction.services.list.1': 'Bezpłatna wycena nieruchomości',
    'transaction.services.list.2': 'Kompleksowa analiza prawna',
    'transaction.services.list.3': 'Profesjonalne negocjacje cenowe',
    'transaction.services.list.4': 'Przygotowanie dokumentów',
    'transaction.services.list.5': 'Pełna obsługa notarialna',
    'transaction.services.list.6': 'Wsparcie w uzyskaniu kredytu',
    'transaction.services.list.7': 'Ubezpieczenie nieruchomości',
    'transaction.services.list.8': 'Przekazanie kluczy i dokumentów',
    'transaction.services.list.9': 'Doradztwo podatkowe',
    'transaction.services.list.10': 'Wsparcie posprzedażowe',
    'transaction.services.list.11': 'Pomoc w przeprowadzce',
    'transaction.services.list.12': 'Zarządzanie najmem (opcjonalnie)',
    'transaction.time.title': 'CZAS TRANSAKCJI',
    'transaction.time.subtitle': 'Średni czas realizacji',
    'transaction.time.apartment_sale': 'Sprzedaż mieszkania',
    'transaction.time.apartment_buy': 'Zakup mieszkania',
    'transaction.time.house_sale': 'Sprzedaż domu',
    'transaction.time.premium_investments': 'Inwestycje premium',
    'transaction.cta.title': 'GOTOWY NA',
    'transaction.cta.title.span': 'TRANSAKCJĘ?',
    'transaction.cta.description': 'Skontaktuj się z nami już dziś i rozpocznij bezpieczny proces sprzedaży lub zakupu nieruchomości',
    
    // Location Page
    'location.hero.title': 'LOKALIZACJE W',
    'location.hero.title.span': 'KRAKOWIE',
    'location.hero.description': 'Odkryj najlepsze dzielnice Krakowa. Każda z nich oferuje unikalny charakter i różnorodne możliwości inwestycyjne.',
    'location.amenities.title': 'DLACZEGO',
    'location.amenities.title.span': 'KRAKÓW?',
    'location.amenities.description': 'Kraków to miasto o wyjątkowej jakości życia, które łączy historię z nowoczesnością',
    'location.amenities.transport': 'Komunikacja',
    'location.amenities.cafes': 'Kawiarnie',
    'location.amenities.restaurants': 'Restauracje',
    'location.amenities.culture': 'Kultura',
    'location.districts.title': 'POPULARNE',
    'location.districts.title.span': 'DZIELNICE',
    'location.districts.description': 'Sprawdź naszą ofertę w najpopularniejszych dzielnicach Krakowa',
    'location.districts.attractions': 'Główne atrakcje:',
    'location.investment.title': 'POTENCJAŁ',
    'location.investment.title.span': 'INWESTYCYJNY',
    'location.investment.description': 'Kraków to jeden z najdynamiczniej rozwijających się rynków nieruchomości w Polsce. Miasto oferuje doskonałe perspektywy dla inwestorów długoterminowych.',
    'location.investment.growth': 'Wzrost cen rok do roku',
    'location.investment.yield': 'Rentowność wynajmu',
    'location.investment.demand': 'Popyt na wynajem',
    'location.investment.demand.high': 'Bardzo wysoki',
    'location.investment.residents': 'Mieszkańców',
    'location.investment.students': 'Studentów',
    'location.investment.tourists': 'Turystów rocznie',
    'location.investment.companies': 'Międzynarodowych firm',
    
    // Investment Page
    'investment.hero.title': 'INWESTYCJE',
    'investment.hero.title.span': 'NIERUCHOMOŚCI',
    'investment.hero.description': 'Profesjonalne doradztwo inwestycyjne w nieruchomości. Buduj swoje bogactwo z Partners International.',
    'investment.types.title': 'RODZAJE',
    'investment.types.title.span': 'INWESTYCJI',
    'investment.types.description': 'Różnorodne możliwości inwestycyjne dostosowane do Twoich celów finansowych',
    'investment.portfolios.title': 'SUGEROWANE',
    'investment.portfolios.title.span': 'PORTFELE',
    'investment.portfolios.description': 'Przykładowe alokacje kapitału w zależności od profilu ryzyka inwestora',
    'investment.calculator.title': 'KALKULATOR',
    'investment.calculator.title.span': 'INWESTYCJI',
    'investment.calculator.description': 'Sprawdź potencjalny zwrot z Twojej inwestycji w nieruchomości. Nasze narzędzie uwzględnia wszystkie kluczowe czynniki rynkowe.',
    'investment.start': 'ROZPOCZNIJ',
    'investment.start.adventure': 'PRZYGODĘ INWESTYCYJNĄ',

    // Investment Search Page
    'investment.search.unified.title': 'SZUKAJ',
    'investment.search.unified.title.span': 'INWESTYCJI',
    'investment.search.unified.description': 'Znajdź idealną inwestycję dopasowaną do Twoich potrzeb, stylu życia lub wymarzonej lokalizacji.',
    'investment.search.unified.tab.investment': 'Według inwestycji',
    'investment.search.unified.tab.lifestyle': 'Według stylu życia',
    'investment.search.unified.tab.location': 'Według lokalizacji',
    'investment.search.page.title': 'Szukaj według inwestycji',
    'investment.search.page.description': 'Znajdź idealną inwestycję dopasowaną do Twoich potrzeb',
    'investment.search.filters.title': 'Filtry wyszukiwania',
    'investment.search.investment.name': 'Nazwa inwestycji',
    'investment.search.investment.name.placeholder': 'Wpisz nazwę...',
    'investment.search.location': 'Lokalizacja',
    'investment.search.location.placeholder': 'Wybierz miasto',
    'investment.search.city.warszawa': 'Warszawa',
    'investment.search.city.krakow': 'Kraków',
    'investment.search.city.gdansk': 'Gdańsk',
    'investment.search.city.wroclaw': 'Wrocław',
    'investment.search.investment.type': 'Typ inwestycji',
    'investment.search.type.placeholder': 'Wybierz typ',
    'investment.search.type.residential': 'Mieszkaniowe',
    'investment.search.type.office': 'Biurowe',
    'investment.search.type.commercial': 'Handlowe',
    'investment.search.type.mixed': 'Mieszane',
    'investment.search.status': 'Status',
    'investment.search.status.placeholder': 'Wybierz status',
    'investment.search.status.sale': 'W sprzedaży',
    'investment.search.status.construction': 'W budowie',
    'investment.search.status.planning': 'W planowaniu',
    'investment.search.status.completed': 'Ukończone',
    'investment.search.button': 'Szukaj',
    'investment.search.recommended': 'Polecane inwestycje',
    'investment.search.cta.title': 'Nie znalazłeś idealnej inwestycji?',
    'investment.search.cta.description': 'Skontaktuj się z naszymi ekspertami - pomożemy Ci znaleźć perfekcyjną okazję inwestycyjną',
    'investment.search.cta.button': 'Umów konsultację',

    // Investment Search translations
    'investment.search.hero.title': 'Znajdź Idealną',
    'investment.search.hero.title.span': 'Inwestycję',
    'investment.search.hero.description': 'Odkryj najlepsze możliwości inwestycyjne w Polsce. Profesjonalne doradztwo i kompleksowa obsługa.',
    'investment.search.filters.location': 'Lokalizacja',
    'investment.search.filters.type': 'Typ nieruchomości',
    'investment.search.filters.price_range': 'Zakres cenowy',
    'investment.search.filters.area': 'Powierzchnia',
    'investment.search.hero.button': 'Rozpocznij wyszukiwanie',

    // Investment New translations  
    'investment.new.page.title': 'Nowe Inwestycje',
    'investment.new.page.description': 'Odkryj najnowsze projekty inwestycyjne na rynku nieruchomości premium',
    'investment.new.stats.new': 'Nowych inwestycji',
    'investment.new.stats.luxury': 'Projektów luksusowych',
    'investment.new.stats.cities': 'Miast',
    'investment.new.stats.avg_price': 'Średnia cena PLN',
    'investment.new.categories.all': 'Wszystkie',
    'investment.new.categories.luxury': 'Luksusowe',
    'investment.new.categories.eco': 'Ekologiczne',
    'investment.new.categories.office': 'Biurowe',
    'investment.new.badge.new': 'NOWE',
    'investment.new.price_from': 'Od',
    'investment.new.key_features': 'Kluczowe cechy',
    'investment.new.view_details': 'Zobacz szczegóły',
    'investment.new.register': 'Zarejestruj się',
    'investment.new.cta.title': 'Bądź na bieżąco z nowymi inwestycjami',
    'investment.new.cta.description': 'Otrzymuj informacje o najnowszych projektach jako pierwszy',
    'investment.new.cta.button': 'Zapisz się do newslettera',

    // Investment features
    'investment.features.taras_widokowy': 'Taras widokowy',
    'investment.features.concierge': 'Concierge 24/7', 
    'investment.features.spa': 'SPA',
    'investment.features.parking_podziemny': 'Parking podziemny',
    'investment.features.panele_sloneczne': 'Panele słoneczne',
    'investment.features.zielen_pionowa': 'Zieleń pionowa',
    'investment.features.ladowarki_ev': 'Ładowarki EV',
    'investment.features.ogrody_spoleczne': 'Ogrody społeczne',
    'investment.features.smart_building': 'Smart building',
    'investment.features.konferencyjne': 'Konferencyjne',
    'investment.features.fitness': 'Fitness',
    'investment.features.restauracja': 'Restauracja',

    // Dates
    'investment.dates.january': 'Styczeń',
    'investment.dates.february': 'Luty',
    'investment.dates.march': 'Marzec',
    'investment.dates.april': 'Kwiecień',
    'investment.dates.may': 'Maj',
    'investment.dates.june': 'Czerwiec',

    // Categories detailed
    'investment.categories.luxury.title': 'Luksusowe inwestycje',
    'investment.categories.luxury.description': 'Filtrowane wyniki dla kategorii luksusowej',
    'investment.categories.eco.title': 'Ekologiczne inwestycje', 
    'investment.categories.eco.description': 'Filtrowane wyniki dla kategorii ekologicznej',
    'investment.categories.office.title': 'Inwestycje biurowe',
    'investment.categories.office.description': 'Filtrowane wyniki dla kategorii biurowej',

    // Lifestyle Search Page
    'lifestyle.page.title': 'Szukaj według stylu życia',
    'lifestyle.page.description': 'Znajdź nieruchomość idealnie dopasowaną do Twojego stylu życia',
    'lifestyle.family.title': 'Rodzinny',
    'lifestyle.family.description': 'Idealne dla rodzin z dziećmi',
    'lifestyle.business.title': 'Biznesowy',
    'lifestyle.business.description': 'Dla profesjonalistów i przedsiębiorców',
    'lifestyle.active.title': 'Aktywny',
    'lifestyle.active.description': 'Dla miłośników sportu i aktywności',
    'lifestyle.luxury.title': 'Luksusowy',
    'lifestyle.luxury.description': 'Najwyższa jakość życia',
    'lifestyle.eco.title': 'Ekologiczny',
    'lifestyle.eco.description': 'Zrównoważony styl życia',
    'lifestyle.urban.title': 'Miejski',
    'lifestyle.urban.description': 'Życie w centrum miasta',
    'lifestyle.key_features': 'Kluczowe cechy:',
    'lifestyle.properties_available': 'dostępnych nieruchomości',
    'lifestyle.view_offers': 'Zobacz oferty',
    'lifestyle.recommended': 'Polecane nieruchomości',
    'lifestyle.style': 'Styl:',
    'lifestyle.area': 'Powierzchnia:',
    'lifestyle.amenities': 'Udogodnienia:',
    'lifestyle.view_details': 'Zobacz szczegóły',
    'lifestyle.quiz.title': 'Nie wiesz jaki styl życia do Ciebie pasuje?',
    'lifestyle.quiz.description': 'Wypełnij nasz krótki quiz, a pomożemy Ci znaleźć idealną nieruchomość',
    'lifestyle.quiz.button': 'Rozpocznij quiz',

    // Location Search Page
    'investment.location.page.title': 'Szukaj według lokalizacji',
    'investment.location.page.description': 'Znajdź idealną inwestycję w najlepszych lokalizacjach w Polsce. Odkryj ekskluzywne projekty w prestiżowych dzielnicach miast.',
    'investment.location.search.title': 'Wyszukiwarka lokalizacji',
    'investment.location.city': 'Miasto',
    'investment.location.city.placeholder': 'Wybierz miasto',
    'investment.location.district': 'Dzielnica/Obszar',
    'investment.location.district.placeholder': 'np. Śródmieście',
    'investment.location.radius': 'Promień (km)',
    'investment.location.radius.placeholder': 'Zasięg',
    'investment.location.radius.1km': '1 km',
    'investment.location.radius.3km': '3 km',
    'investment.location.radius.5km': '5 km',
    'investment.location.radius.10km': '10 km',
    'investment.location.search.button': 'Szukaj',
    'investment.location.tabs.featured': 'Polecane',
    'investment.location.tabs.all': 'Wszystkie miasta',
    'investment.location.tabs.filters': 'Zaawansowane filtry',
    'investment.location.featured.badge': 'POLECANE',
    'investment.location.projects.count': 'projektów',
    'investment.location.price_range': 'Zakres cen',
    'investment.location.view_projects': 'Zobacz projekty',
    'investment.location.map': 'Mapa',
    'investment.location.browse': 'Przeglądaj',
    'investment.location.price': 'Cena',
    'investment.location.type': 'Typ',
    'investment.location.area': 'Powierzchnia',
    'investment.location.rooms': 'Pokoje',
    'investment.location.price.up_to_500k': 'Do 500k PLN',
    'investment.location.price.500k_1m': '500k - 1M PLN',
    'investment.location.price.1m_2m': '1M - 2M PLN',
    'investment.location.price.over_2m': 'Powyżej 2M PLN',
    'investment.location.type.apartment': 'Apartament',
    'investment.location.type.house': 'Dom',
    'investment.location.type.loft': 'Loft',
    'investment.location.type.penthouse': 'Penthouse',
    'investment.location.area.up_to_50': 'Do 50m²',
    'investment.location.area.50_100': '50-100m²',
    'investment.location.area.100_150': '100-150m²',
    'investment.location.area.over_150': 'Powyżej 150m²',
    'investment.location.rooms.1': '1',
    'investment.location.rooms.2': '2',
    'investment.location.rooms.3': '3',
    'investment.location.rooms.4plus': '4+',
    'investment.location.apply_filters': 'Zastosuj filtry',
    'investment.location.cta.title': 'Nie znalazłeś idealnej lokalizacji?',
    'investment.location.cta.description': 'Skontaktuj się z naszymi ekspertami, którzy pomogą Ci znaleźć inwestycję w wymarzonej lokalizacji dostosowanej do Twoich potrzeb i budżetu.',
    'investment.location.cta.consultation': 'Bezpłatna konsultacja',
    'investment.location.cta.contact': 'Zostaw kontakt',

    // Main page sections
    'featured.properties.title': 'OFERTY LUKSUSOWYCH',
    'featured.properties.title.span': 'NIERUCHOMOŚCI',
    'featured.properties.subtitle': 'OFERTY',
    'services.special.meeting': 'WYJĄTKOWE SPOTKANIE',
    'services.special.meeting.subtitle': 'DLA KLIENTÓW PARTNERS INTERNATIONAL',
    'services.foreign.properties': 'NIERUCHOMOŚCI',
    'services.foreign.properties.subtitle': 'ZAGRANICZNYCH',
    'services.first.class': 'FIRST CLASS EXPERIENCE',
    'services.first.class.subtitle': 'TEAM DELUXE',
    'services.secret.offers': 'POZNAJ SEKRETNE OFERTY',
    'services.secret.offers.subtitle': 'LUKSUSOWYCH NIERUCHOMOŚCI',
    'services.read_more': 'CZYTAJ WIĘCEJ',
    'services.see': 'ZOBACZ',
    'services.learn_more': 'DOWIEDZ SIĘ WIĘCEJ',
    
    // Services Page
    'services.hero.title': 'NASZE',
    'services.hero.title.span': 'USŁUGI',
    'services.hero.description': 'Kompleksowe usługi na rynku nieruchomości w Krakowie. Od wyceny po zarządzanie - wszystko w jednym miejscu.',
    'services.main.title': 'GŁÓWNE',
    'services.main.title.span': 'USŁUGI',
    'services.main.description': 'Profesjonalne usługi nieruchomości dostosowane do Twoich potrzeb',
    'services.additional.title': 'USŁUGI',
    'services.additional.title.span': 'DODATKOWE',
    'services.additional.description': 'Rozszerz swoje możliwości dzięki naszym specjalistycznym usługom',
    'services.process.title': 'JAK',
    'services.process.title.span': 'PRACUJEMY?',
    'services.process.description': 'Nasz sprawdzony proces gwarantuje najwyższą jakość obsługi',
    'services.support.title': 'WSPARCIE',
    'services.support.title.span': '24/7',
    'services.support.description': 'Nasz zespek ekspertów jest dostępny przez całą dobę. Otrzymasz profesjonalne wsparcie na każdym etapie współpracy.',
    
    // Common Lorem
    'lorem.short': 'Najwyższej klasy nieruchomości w najlepszych lokalizacjach. Profesjonalne doradztwo i kompleksowa obsługa.',
    'lorem.medium': 'Specjalizujemy się w sprzedaży ekskluzywnych nieruchomości w Polsce i za granicą. Nasz zespół ekspertów zapewnia profesjonalne doradztwo na każdym etapie transakcji, gwarantując najwyższy poziom obsługi.',
    'lorem.long': 'Partners International to wiodąca firma na rynku luksusowych nieruchomości. Od ponad dekady pomagamy klientom w realizacji ich marzeń o idealnym mieszkaniu czy domu. Nasze portfolio obejmuje najcenniejsze nieruchomości w prestiżowych lokalizacjach w całej Polsce.',
    
    // Navigation - Additional Menu Items
    'nav.investments': 'INWESTYCJE',
    'nav.about': 'O AGENCJI',
    'nav.investments.search': 'Szukaj wg inwestycji',
    'nav.investments.new': 'Nowe inwestycje',
    'nav.investments.lifestyle': 'Szukaj wg stylu życia',
    'nav.investments.location': 'Szukaj wg lokalizacji',
    'nav.services.marketing': 'Marketing nieruchomości',
    'nav.services.sellers': 'Dla sprzedających',
    'nav.services.buyers': 'Dla kupujących',
    'nav.services.landlords': 'Dla wynajmujących',
    'nav.services.tenants': 'Dla najemców',
    'nav.services.interiors': 'Wykończenie wnętrz',
    'nav.about.us': 'O NAS',
    'nav.about.team': 'ZESPÓŁ',
    'nav.about.blog': 'BLOG',
    'nav.about.career': 'KARIERA',
    'nav.about.office': 'NASZE BIURO',
    'nav.about.media': 'W MEDIACH',
    
    // About Us Page
    'about.hero.title': 'O',
    'about.hero.title.span': 'NAS',
    'about.hero.description': 'Premium Partners International to więcej niż agencja nieruchomości. To zespół pasjonatów, którzy od ponad dekady pomagają klientom realizować marzenia o idealnym domu. Nasza historia to opowieść o ciągłym dążeniu do doskonałości i budowaniu trwałych relacji.',
    'about.mission.title': 'NASZA',
    'about.mission.title.span': 'MISJA',
    'about.mission.description.1': 'Wierzymy, że każdy zasługuje na wyjątkowy dom. Naszą misją jest łączenie ludzi z nieruchomościami, które nie tylko spełniają ich potrzeby, ale przekraczają oczekiwania. Specjalizujemy się w segmencie premium, gdzie każdy detal ma znaczenie.',
    'about.mission.description.2': 'Przez lata zbudowaliśmy reputację opartą na zaufaniu, profesjonalizmie i indywidualnym podejściu do każdego klienta. Nasza wiedza o rynku, połączona z nowoczesnymi technologiami, pozwala nam oferować usługi najwyższej jakości.',
    'about.achievements.title': 'NASZE',
    'about.achievements.title.span': 'OSIĄGNIĘCIA',
    'about.achievements.description': 'Liczby, które mówią same za siebie o naszym doświadczeniu i sukcesach',
    'about.achievement.transactions': 'Zrealizowanych transakcji',
    'about.achievement.transactions.desc': 'Pomogliśmy ponad 500 klientom znaleźć wymarzone mieszkania',
    'about.achievement.value': 'Wartość sprzedanych nieruchomości',
    'about.achievement.value.desc': 'PLN w luksusowych nieruchomościach sprzedanych przez nasz zespół',
    'about.achievement.satisfaction': 'Zadowolonych klientów',
    'about.achievement.satisfaction.desc': 'Nasi klienci polecają nas znajomym i rodzinie',
    'about.achievement.awards': 'Nagród branżowych',
    'about.achievement.awards.desc': 'Docenieni przez ekspertów za jakość usług',
    'about.history.title': 'NASZA',
    'about.history.title.span': 'HISTORIA',
    'about.history.description': 'Podróż od początków do lidera rynku nieruchomości premium',
    'about.values.title': 'CO NAS',
    'about.values.title.span': 'WYRÓŻNIA',
    'about.values.individual.title': 'Indywidualne podejście',
    'about.values.individual.desc': 'Każdy klient jest dla nas wyjątkowy. Dostosowujemy nasze usługi do konkretnych potrzeb i oczekiwań.',
    'about.values.portfolio.title': 'Ekskluzywne portfolio',
    'about.values.portfolio.desc': 'Oferujemy najlepsze nieruchomości premium w najpiękniejszych lokalizacjach Krakowa i okolic.',
    'about.values.international.title': 'Międzynarodowy zasięg',
    'about.values.international.desc': 'Współpracujemy z klientami z całego świata, oferując usługi w wielu językach.',
    
    // Privacy Policy Page
    'privacy.title': 'Polityka Prywatności',
    'privacy.section1.title': '1. Informacje ogólne',
    'privacy.section2.title': '2. Przetwarzanie danych osobowych',
    'privacy.section3.title': '3. Cookies i technologie śledzące',
    'privacy.section4.title': '4. Prawa użytkownika',
    'privacy.section5.title': '5. Kontakt',
    
    // For Landlords Page
    'landlords.hero.title': 'Dla wynajmujących',
    'landlords.hero.description': 'Profesjonalne zarządzanie wynajmem nieruchomości. Znajdziemy rzetelnych najemców i zapewnimy bezproblemowy najem.',
    'landlords.benefits.title': 'Dlaczego warto nam zaufać?',
    'landlords.services.tab': 'Nasze usługi',
    'landlords.packages.tab': 'Pakiety',
    'landlords.process.tab': 'Proces',
    'landlords.service.finding.title': 'Znajdowanie najemców',
    'landlords.service.finding.description': 'Szybkie znalezienie rzetelnych najemców',
    'landlords.service.management.title': 'Zarządzanie najmem',
    'landlords.service.management.description': 'Kompleksowa obsługa wynajmu',
    'landlords.service.legal.title': 'Obsługa prawna',
    'landlords.service.legal.description': 'Bezpieczeństwo prawne wynajmu',
    'landlords.service.optimization.title': 'Optymalizacja zysków',
    'landlords.service.optimization.description': 'Maksymalizacja dochodów z wynajmu',
    'landlords.package.basic.name': 'Tylko znajdowanie najemcy',
    'landlords.package.basic.price': 'Jednorazowo 50% miesięcznego czynszu',
    'landlords.package.basic.description': 'Znajdziemy i sprawdzimy najemcę',
    'landlords.package.full.name': 'Pełne zarządzanie',
    'landlords.package.full.price': '8% miesięcznego czynszu',
    'landlords.package.full.description': 'Kompleksowa obsługa wynajmu',
    'landlords.package.premium.name': 'Zarządzanie premium',
    'landlords.package.premium.price': '12% miesięcznego czynszu',
    'landlords.package.premium.description': 'Najwyższy poziom obsługi',
    'landlords.cta.title': 'Wynajmij swoją nieruchomość z ekspertami',
    'landlords.cta.description': 'Skontaktuj się z nami i zobacz, jak możemy pomóc Ci w bezproblemowym wynajmie nieruchomości z gwarancją najlepszych najemców.',
    
    // For Sellers Page  
    'sellers.hero.title': 'Dla sprzedających',
    'sellers.hero.description': 'Profesjonalna obsługa sprzedaży nieruchomości. Pomożemy Ci sprzedać nieruchomość po najlepszej cenie w najkrótszym czasie.',
    
    // For Buyers Page
    'buyers.hero.title': 'Dla kupujących', 
    'buyers.hero.description': 'Pomożemy Ci znaleźć i kupić idealną nieruchomość dopasowaną do Twoich potrzeb, budżetu i stylu życia.',
    
    // For Tenants Page
    'tenants.hero.title': 'Dla najemców',
    'tenants.hero.description': 'Profesjonalna pomoc w wynajmie. Pomożemy Ci znaleźć idealne mieszkanie lub dom do wynajęcia.',
    
    // Marketing Service Page
    'marketing.hero.title': 'Usługi marketingowe',
    'marketing.hero.description': 'Profesjonalny marketing nieruchomości, który sprzedaje. Tworzymy kampanie, które przyciągają odpowiednich kupujących.',

    // Blog Page
    'blog.title': 'BLOG',
    'blog.title.span': 'PREMIUM',
    'blog.description': 'Najnowsze trendy, analizy rynku i profesjonalne porady z świata nieruchomości luksusowych. Bądź na bieżąco z ekspertami Premium Partners International.',
    'blog.categories.all': 'Wszystkie',
    'blog.categories.trends': 'Trendy',
    'blog.categories.investments': 'Inwestycje',
    'blog.categories.advice': 'Porady',
    'blog.categories.analysis': 'Analiza',
    'blog.categories.luxury': 'Luksus',
    'blog.categories.law': 'Prawo',
    'blog.featured': 'POLECANE',
    'blog.featured.articles': 'ARTYKUŁY',
    'blog.all': 'WSZYSTKIE',
    'blog.all.articles': 'ARTYKUŁY',
    'blog.read_more': 'Czytaj więcej',
    'blog.read': 'Czytaj',
    'blog.load_more': 'Załaduj więcej artykułów',

    // Career Page
    'career.title': 'KARIERA',
    'career.title.span': 'Z NAMI',
    'career.description': 'Dołącz do naszego zespołu profesjonalistów na rynku nieruchomości. Oferujemy atrakcyjne możliwości rozwoju kariery w dynamicznej i rozwijającej się firmie.',
    'career.why.title': 'DLACZEGO WARTO',
    'career.why.title.span': 'Z NAMI PRACOWAĆ?',
    'career.benefits.title': 'BENEFITY I',
    'career.benefits.title.span': 'MOŻLIWOŚCI',
    'career.positions.title': 'AKTUALNE',
    'career.positions.title.span': 'OFERTY',
    'career.apply': 'Aplikuj',
    'career.send_cv': 'Wyślij CV',

    // Team Page
    'team.title': 'NASZ',
    'team.title.span': 'ZESPÓŁ',
    'team.description': 'Poznaj nasz zespół doświadczonych profesjonalistów na rynku nieruchomości. Każdy członek zespołu wnosi unikalne umiejętności i rozległą wiedzę o rynku.',
    'team.leadership.title': 'KADRA',
    'team.leadership.title.span': 'KIEROWNICZA',
    'team.agents.title': 'AGENCI',
    'team.agents.title.span': 'NIERUCHOMOŚCI',
    'team.support.title': 'ZESPÓŁ',
    'team.support.title.span': 'WSPARCIA',
    'team.contact': 'Kontakt',

    // Office Page
    'office.title': 'NASZE',
    'office.title.span': 'BIURO',
    'office.description': 'Odwiedź nasze nowoczesne biuro w sercu Warszawy. Zapewniamy komfortowe warunki do spotkań i konsultacji.',
    'office.location.title': 'LOKALIZACJA',
    'office.location.title.span': 'BIURA',
    'office.hours.title': 'GODZINY',
    'office.hours.title.span': 'OTWARCIA',
    'office.contact.title': 'DANE',
    'office.contact.title.span': 'KONTAKTOWE',
    'office.visit': 'Umów wizytę',

    // Media Page
    'media.title': 'W',
    'media.title.span': 'MEDIACH',
    'media.description': 'Zobacz, co media mówią o nas. Nasze osiągnięcia i ekspertyza są regularnie prezentowane w wiodących publikacjach branżowych.',
    'media.press.title': 'MATERIAŁY',
    'media.press.title.span': 'PRASOWE',
    'media.awards.title': 'NAGRODY I',
    'media.awards.title.span': 'WYRÓŻNIENIA',
    'media.interviews.title': 'WYWIADY I',
    'media.interviews.title.span': 'OPINIE',

    // Calculator Page
    'calculator.title': 'KALKULATOR',
    'calculator.title.span': 'INWESTYCJI',
    'calculator.description': 'Oblicz potencjalny zwrot z Twojej inwestycji w nieruchomości. Nasze zaawansowane narzędzie uwzględnia wszystkie czynniki rynkowe.',
    'calculator.property_value': 'Wartość nieruchomości',
    'calculator.down_payment': 'Wkład własny',
    'calculator.loan_term': 'Okres kredytowania',
    'calculator.interest_rate': 'Oprocentowanie',
    'calculator.rental_income': 'Miesięczny dochód z wynajmu',
    'calculator.calculate': 'Oblicz',
    'calculator.results': 'Wyniki',
    'calculator.monthly_payment': 'Miesięczna rata',
    'calculator.total_cost': 'Całkowity koszt',
    'calculator.roi': 'Zwrot z inwestycji',

    // Contact Page
    'contact.page.title': 'SKONTAKTUJ SIĘ',
    'contact.page.title.span': 'Z NAMI',
    'contact.page.description': 'Skontaktuj się z naszymi ekspertami. Jesteśmy tutaj, aby pomóc Ci we wszystkich sprawach związanych z nieruchomościami.',
    'contact.form.title': 'WYŚLIJ NAM',
    'contact.form.title.span': 'WIADOMOŚĆ',
    'contact.office.title': 'INFORMACJE O',
    'contact.office.title.span': 'BIURZE',
    'contact.social.title': 'ŚLEDŹ',
    'contact.social.title.span': 'NAS',

    // Terms Page
    'terms.title': 'Regulamin',
    'terms.section1.title': '1. Postanowienia ogólne',
    'terms.section2.title': '2. Usługi',
    'terms.section3.title': '3. Odpowiedzialność',
    'terms.section4.title': '4. Postanowienia końcowe',

    // Cookies Page
    'cookies.title': 'Polityka Cookies',
    'cookies.section1.title': '1. Czym są pliki cookies',
    'cookies.section2.title': '2. Rodzaje cookies, które stosujemy',
    'cookies.section3.title': '3. Jak zarządzać plikami cookies',
    'cookies.section4.title': '4. Informacje kontaktowe',

    // Consultation Page
    'consultation.title': 'BEZPŁATNA',
    'consultation.title.span': 'KONSULTACJA',
    'consultation.description': 'Umów bezpłatną konsultację z naszymi ekspertami ds. nieruchomości. Pomożemy Ci znaleźć idealną nieruchomość lub opracować strategię inwestycyjną.',
    'consultation.book': 'Umów konsultację',
    'consultation.benefits.title': 'KORZYŚCI Z',
    'consultation.benefits.title.span': 'KONSULTACJI',

    // Service Detail Pages
    'service.marketing.title': 'MARKETING',
    'service.marketing.title.span': 'NIERUCHOMOŚCI',
    'service.sellers.title': 'DLA',
    'service.sellers.title.span': 'SPRZEDAJĄCYCH',
    'service.buyers.title': 'DLA',
    'service.buyers.title.span': 'KUPUJĄCYCH',
    'service.landlords.title': 'DLA',
    'service.landlords.title.span': 'WYNAJMUJĄCYCH',
    'service.tenants.title': 'DLA',
    'service.tenants.title.span': 'NAJEMCÓW',
    'service.interiors.title': 'WYKOŃCZENIE',
    'service.interiors.title.span': 'WNĘTRZ',

    // Investment Search Pages
    'investment.search.title': 'SZUKAJ',
    'investment.search.title.span': 'INWESTYCJI',
    'investment.new.title': 'NOWE',
    'investment.new.title.span': 'INWESTYCJE',
    'investment.lifestyle.title': 'SZUKAJ WG',
    'investment.lifestyle.title.span': 'STYLU ŻYCIA',

    // Property Detail Page
    'property.details.title': 'SZCZEGÓŁY',
    'property.details.title.span': 'NIERUCHOMOŚCI',
    'property.gallery': 'Galeria zdjęć',
    'property.description': 'Opis',
    'property.features': 'Cechy',
    'property.location.details': 'Lokalizacja',
    'property.price': 'Cena',
    'property.area': 'Powierzchnia',
    'property.rooms': 'Pokoje',
    'property.floor': 'Piętro',
    'property.year': 'Rok budowy',
    'property.contact_agent': 'Kontakt z agentem',
    'property.schedule_viewing': 'Umów oglądanie',
    'property.similar': 'Podobne nieruchomości',

    // Location page districts
    'location.district.stare_miasto.name': 'Stare Miasto',
    'location.district.stare_miasto.description': 'Serce Krakowa z zabytkowymi kamienicami i Rynkiem Głównym. Najdroższa i najbardziej prestiżowa lokalizacja w mieście.',
    'location.district.stare_miasto.properties': '47 nieruchomości',
    'location.district.stare_miasto.highlight.1': 'Rynek Główny',
    'location.district.stare_miasto.highlight.2': 'Sukiennice',
    'location.district.stare_miasto.highlight.3': 'Kościół Mariacki',
    'location.district.stare_miasto.highlight.4': 'Uniwersytet Jagielloński',

    'location.district.kazimierz.name': 'Kazimierz',
    'location.district.kazimierz.description': 'Artystyczna dzielnica z bogatą historią żydowską i żywym życiem nocnym. Centrum kulturalne Krakowa z licznymi galeriami i klubami.',
    'location.district.kazimierz.properties': '32 nieruchomości',
    'location.district.kazimierz.highlight.1': 'Synagoga Remuh',
    'location.district.kazimierz.highlight.2': 'Plac Nowy',
    'location.district.kazimierz.highlight.3': 'Klimatyczne kawiarnie',
    'location.district.kazimierz.highlight.4': 'Nocne życie',

    'location.district.podgorze.name': 'Podgórze',
    'location.district.podgorze.description': 'Dynamicznie rozwijająca się dzielnica z nowoczesnymi inwestycjami. Dawna dzielnica przemysłowa przekształcana w nowoczesne centrum biznesu.',
    'location.district.podgorze.properties': '28 nieruchomości',
    'location.district.podgorze.highlight.1': 'Muzeum Schindlera',
    'location.district.podgorze.highlight.2': 'Kładka Bernatka',
    'location.district.podgorze.highlight.3': 'Galeria Kazimierz',
    'location.district.podgorze.highlight.4': 'Forum Przestrzenie',

    'location.district.zwierzyniec.name': 'Zwierzyniec',
    'location.district.zwierzyniec.description': 'Spokojna dzielnica z dużą ilością zieleni i prestiżowymi lokalizacjami. Idealna dla rodzin ceniących ciszę i dostęp do natury.',
    'location.district.zwierzyniec.properties': '21 nieruchomości',
    'location.district.zwierzyniec.highlight.1': 'Las Wolski',
    'location.district.zwierzyniec.highlight.2': 'Kopiec Kościuszki',
    'location.district.zwierzyniec.highlight.3': 'Zoo Kraków',
    'location.district.zwierzyniec.highlight.4': 'Klasztor Salwatorianów',

    'location.district.zablocie.name': 'Zabłocie',
    'location.district.zablocie.description': 'Nowoczesna dzielnica biznesowa z loftami i biurowcami. Centrum startupów i firm technologicznych w Krakowie.',
    'location.district.zablocie.properties': '35 nieruchomości',
    'location.district.zablocie.highlight.1': 'Muzeum Sztuki Współczesnej',
    'location.district.zablocie.highlight.2': 'Lofty',
    'location.district.zablocie.highlight.3': 'Business Garden',
    'location.district.zablocie.highlight.4': 'Hub technologiczny',

    'location.district.bronowice.name': 'Bronowice',
    'location.district.bronowice.description': 'Rodzinna dzielnica z domami jednorodzinnymi i spokojną atmosferą. Doskonała komunikacja z centrum i rozwiniętą infrastrukturą.',
    'location.district.bronowice.properties': '19 nieruchomości',
    'location.district.bronowice.highlight.1': 'Parki miejskie',
    'location.district.bronowice.highlight.2': 'Szkoły podstawowe',
    'location.district.bronowice.highlight.3': 'Centra handlowe',
    'location.district.bronowice.highlight.4': 'Komunikacja tramwajowa',

    'location.district.grzegorzki.name': 'Grzegórzki',
    'location.district.grzegorzki.description': 'Szybko rozwijająca się dzielnica z nowymi inwestycjami mieszkaniowymi. Dobra lokalizacja z dostępem do centrum.',
    'location.district.grzegorzki.properties': '24 nieruchomości',
    'location.district.grzegorzki.highlight.1': 'Nowe osiedla',
    'location.district.grzegorzki.highlight.2': 'Dobre ceny',
    'location.district.grzegorzki.highlight.3': 'Blisko centrum',
    'location.district.grzegorzki.highlight.4': 'Rozwój infrastruktury',

    'location.district.pradnik.name': 'Prądnik Czerwony',
    'location.district.pradnik.description': 'Popularna dzielnica mieszkaniowa z dobrą infrastrukturą i dostępnymi cenami. Idealna dla pierwszego mieszkania.',
    'location.district.pradnik.properties': '31 nieruchomości',
    'location.district.pradnik.highlight.1': 'Przystępne ceny',
    'location.district.pradnik.highlight.2': 'Dobre połączenia',
    'location.district.pradnik.highlight.3': 'Szpitale',
    'location.district.pradnik.highlight.4': 'Sklepy i usługi',

    // Location buttons
    'location.button.see_all_attractions': 'ZOBACZ WSZYSTKIE ATRAKCJE',
    'location.button.see_offers': 'ZOBACZ OFERTY',

    // Transaction page time periods
    'transaction.time.period.30_45_days': '30-45 dni',
    'transaction.time.period.14_30_days': '14-30 dni',
    'transaction.time.period.45_60_days': '45-60 dni',
    'transaction.time.period.60_90_days': '60-90 dni',

    // Property descriptions  
    'property.description.old_town': 'Luksusowy apartament w sercu Krakowa z widokiem na Sukiennice i Rynek Główny. Wysokie sufity, oryginalne detale architektoniczne.',
    'property.description.kazimierz': 'Ekskluzywny penthouse w artystycznej dzielnicy Krakowa. Taras z panoramicznym widokiem, nowoczesne wykończenia.',
    'property.description.podgorze': 'Odnowiona kamienica z zachowanymi historycznymi elementami. Własny ogród, garaż, eleganckie wnętrza.',
    'property.description.zablocie': 'Nowoczesny loft w dawnej dzielnicy przemysłowej. Industrialny charakter, wysokie okna, open space.',
    'property.description.zwierzyniec': 'Elegancki apartament w spokojnej dzielnicy z zielenią. Balkon z widokiem na park, miejsce parkingowe.',
    'property.description.bronowice': 'Luksusowa willa z ogrodem i basenem. Domofon, monitoring, garaż na 3 samochody, sauna.',
    'property.description.nowa_huta': 'Mieszkanie po remoncie w dobrze skomunikowanej lokalizacji. Blisko centrum handlowego i komunikacji.',
    'property.description.salwator': 'Wyjątkowy penthouse z tarasem dachowym. Widok na Wawel, klimatyzacja, underfloor heating.',

    // Property titles
    'property.title.old_town': 'Apartament w Starym Mieście',
    'property.title.kazimierz': 'Penthouse Kazimierz', 
    'property.title.podgorze': 'Kamienica Podgórze',
    'property.title.zablocie': 'Loft Zabłocie',
    'property.title.zwierzyniec': 'Apartament Zwierzyniec',
    'property.title.bronowice': 'Dom w Bronowicach',
    'property.title.nowa_huta': 'Mieszkanie Nowa Huta',
    'property.title.salwator': 'Penthouse Salwator',

    // Property locations
    'property.location.old_town': 'Kraków, Stare Miasto',
    'property.location.kazimierz': 'Kraków, Kazimierz',
    'property.location.podgorze': 'Kraków, Podgórze', 
    'property.location.zablocie': 'Kraków, Zabłocie',
    'property.location.zwierzyniec': 'Kraków, Zwierzyniec',
    'property.location.bronowice': 'Kraków, Bronowice',  
    'property.location.nowa_huta': 'Kraków, Nowa Huta',
    'property.location.salwator': 'Kraków, Salwator',

    // Search filter text
    'search.title': 'Wyszukaj nieruchomość',
    'search.filters': 'Filtry',
    'search.expand': 'Zwiń',
    'search.collapse': 'Zwiń',
    'search.location.input.placeholder': 'Wpisz lokalizację lub nazwę...',
    'search.type.select.placeholder': 'Typ nieruchomości',
    'search.type.select.apartment': 'Mieszkanie',
    'search.type.select.house': 'Dom',
    'search.type.select.villa': 'Willa',
    'search.type.select.penthouse': 'Penthouse',
    'search.type.select.office': 'Biuro',
    'search.price.from': 'Cena od',
    'search.price.to': 'Cena do', 
    'search.rooms.select.placeholder': 'Liczba pokoi',
    'search.rooms.1': '1 pokój',
    'search.rooms.2': '2 pokoje',
    'search.rooms.3': '3 pokoje',
    'search.rooms.4plus': '4+ pokoje',
    'search.button': 'Szukaj',

    // Badge translations
    'badge.premium': 'PREMIUM',
    'badge.exclusive': 'EKSKLUZYWNE', 
    'badge.new': 'NOWE',
    'badge.opportunity': 'OKAZJA',
    'badge.rent': 'WYNAJEM',

    // Common UI Elements
    'ui.loading': 'Ładowanie...',
    'ui.error': 'Wystąpił błąd',
    'ui.success': 'Sukces',
    'ui.cancel': 'Anuluj',
    'ui.confirm': 'Potwierdź',
    'ui.save': 'Zapisz',
    'ui.edit': 'Edytuj',
    'ui.delete': 'Usuń',
    'ui.close': 'Zamknij',
    'ui.view_more': 'Zobacz więcej',
    'ui.show_less': 'Pokaż mniej',

    // Time and Date
    'time.days': 'dni',
    'time.hours': 'godziny',
    'time.minutes': 'minuty',
    'date.today': 'Dziś',
    'date.yesterday': 'Wczoraj',
    'date.week': 'Tydzień',
    'date.month': 'Miesiąc',
    'date.year': 'Rok',
  },
  en: {
    // Add console log to check if translations are loading  
    'debug.language': 'English',
    // Navigation
    'nav.properties': 'PROPERTIES',
    'nav.transaction': 'TRANSACTION',
    'nav.location': 'LOCATION',
    'nav.investment': 'INVESTMENT',
    'nav.services': 'SERVICES',
    
    // Hero Section
    'hero.badge': 'APARTMENT FOR SALE',
    'hero.title.krakow': 'KRAKOW',
    'hero.title.stare_miasto': 'OLD TOWN',
    'hero.title.rynek_glowny': 'MAIN SQUARE',
    'hero.cta': 'VIEW OFFERS',
    'hero.scroll': 'FIND PROPERTY',
    
    // Properties Page
    'properties.title': 'PROPERTIES IN',
    'properties.title.krakow': 'KRAKOW',
    'properties.search': 'SEARCH',
    'properties.details': 'VIEW DETAILS',
    'properties.load_more': 'LOAD MORE',
    
    // Properties Categories
    'properties.categories.sale': 'FOR SALE',
    'properties.categories.rent': 'FOR RENT',
    'properties.categories.off_market': 'OFF MARKET',
    'properties.categories.deluxe': 'DELUXE ESTATES',
    'properties.category.sale.title': 'PROPERTIES',
    'properties.category.sale.subtitle': 'FOR SALE',
    'properties.category.rent.title': 'PROPERTIES',
    'properties.category.rent.subtitle': 'FOR RENT',
    'properties.category.off_market.title': 'OFF MARKET',
    'properties.category.off_market.subtitle': 'OFFERS',
    'properties.category.deluxe.title': 'DELUXE',
    'properties.category.deluxe.subtitle': 'ESTATES',
    
    // Transaction Page
    'transaction.title': 'TRANSACTION',
    'transaction.title.transaction': 'PROCESS',
    'transaction.start': 'START PROCESS',
    'transaction.consultation': 'BOOK CONSULTATION',
    'transaction.free_valuation': 'FREE VALUATION',
    'transaction.schedule_meeting': 'SCHEDULE MEETING',
    
    // Location Page
    'location.title': 'LOCATIONS IN',
    'location.title.krakow': 'KRAKOW',
    'location.why': 'WHY',
    'location.why.krakow': 'KRAKOW?',
    'location.popular': 'POPULAR',
    'location.popular.districts': 'DISTRICTS',
    'location.potential': 'INVESTMENT',
    'location.potential.investment': 'POTENTIAL',
    'location.analysis': 'INVESTMENT ANALYSIS',
    
    // Investment Page
    'investment.title': 'REAL ESTATE',
    'investment.title.properties': 'INVESTMENTS',
    'investment.types': 'INVESTMENT',
    'investment.types.investments': 'TYPES',
    'investment.suggested': 'SUGGESTED',
    'investment.suggested.portfolios': 'PORTFOLIOS',
    'investment.calculator': 'INVESTMENT',
    'investment.calculator.investment': 'CALCULATOR',
    
    // Services Page
    'services.title': 'OUR',
    'services.title.services': 'SERVICES',
    'services.main': 'MAIN',
    'services.main.services': 'SERVICES',
    'services.additional': 'ADDITIONAL',
    'services.additional.services': 'SERVICES',
    'services.how': 'HOW WE',
    'services.how.we_work': 'WORK?',
    'services.support': 'SUPPORT',
    'services.support.24_7': '24/7',
    
    // Footer
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'SUBSCRIBE',
    'footer.rights': '© 2024 Partners International. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    
    // Contact Dialog
    'contact.title': 'Contact',
    'contact.phone': 'Call us',
    'contact.name': 'Name',
    'contact.name.placeholder': 'Your name',
    'contact.email': 'Email',
    'contact.email.placeholder': 'your@email.com',
    'contact.message': 'Message',
    'contact.message.placeholder': 'Message content...',
    'contact.send': 'Send',
    
    // Footer Services
    'footer.service.sales': 'Real Estate Sales',
    'footer.service.rental': 'Property Rental',
    'footer.service.investment': 'International Investments',
    'footer.service.legal': 'Legal Consulting',
    'footer.service.valuation': 'Property Valuation',
    'footer.newsletter.placeholder': 'Your email address',
    'footer.newsletter.description': 'Receive the latest luxury real estate offers directly to your mailbox.',

    // Blog Page
    'blog.title': 'PREMIUM',
    'blog.title.span': 'BLOG',
    'blog.description': 'Latest trends, market analysis and professional advice from the world of luxury real estate. Stay up to date with Premium Partners International experts.',
    'blog.categories.all': 'All',
    'blog.categories.trends': 'Trends',
    'blog.categories.investments': 'Investments',
    'blog.categories.advice': 'Advice',
    'blog.categories.analysis': 'Analysis',
    'blog.categories.luxury': 'Luxury',
    'blog.categories.law': 'Law',
    'blog.featured': 'FEATURED',
    'blog.featured.articles': 'ARTICLES',
    'blog.all': 'ALL',
    'blog.all.articles': 'ARTICLES',
    'blog.read_more': 'Read more',
    'blog.read': 'Read',
    'blog.load_more': 'Load more articles',

    // Career Page
    'career.title': 'CAREER',
    'career.title.span': 'OPPORTUNITIES',
    'career.description': 'Join our team of real estate professionals. We offer attractive career opportunities in a dynamic and growing company.',
    'career.why.title': 'WHY WORK',
    'career.why.title.span': 'WITH US?',
    'career.benefits.title': 'BENEFITS AND',
    'career.benefits.title.span': 'OPPORTUNITIES',
    'career.positions.title': 'OPEN',
    'career.positions.title.span': 'POSITIONS',
    'career.apply': 'Apply',
    'career.send_cv': 'Send CV',

    // Team Page
    'team.title': 'OUR',
    'team.title.span': 'TEAM',
    'team.description': 'Meet our team of experienced real estate professionals. Each team member brings unique skills and extensive market knowledge.',
    'team.leadership.title': 'LEADERSHIP',
    'team.leadership.title.span': 'TEAM',
    'team.agents.title': 'REAL ESTATE',
    'team.agents.title.span': 'AGENTS',
    'team.support.title': 'SUPPORT',
    'team.support.title.span': 'TEAM',
    'team.contact': 'Contact',

    // Office Page  
    'office.title': 'OUR',
    'office.title.span': 'OFFICE',
    'office.description': 'Visit our modern office in the heart of Warsaw. We provide comfortable conditions for meetings and consultations.',
    'office.location.title': 'OFFICE',
    'office.location.title.span': 'LOCATION',
    'office.hours.title': 'OPENING',
    'office.hours.title.span': 'HOURS',
    'office.contact.title': 'CONTACT',
    'office.contact.title.span': 'DETAILS',
    'office.visit': 'Schedule a visit',

    // Media Page
    'media.title': 'IN THE',
    'media.title.span': 'MEDIA',
    'media.description': 'See what the media says about us. Our achievements and expertise are regularly featured in leading industry publications.',
    'media.press.title': 'PRESS',
    'media.press.title.span': 'COVERAGE',
    'media.awards.title': 'AWARDS AND',
    'media.awards.title.span': 'RECOGNITION',
    'media.interviews.title': 'INTERVIEWS AND',
    'media.interviews.title.span': 'OPINIONS',

    // Calculator Page
    'calculator.title': 'INVESTMENT',
    'calculator.title.span': 'CALCULATOR',
    'calculator.description': 'Calculate potential returns from your real estate investment. Our advanced tool takes into account all market factors.',
    'calculator.property_value': 'Property Value',
    'calculator.down_payment': 'Down Payment',
    'calculator.loan_term': 'Loan Term',
    'calculator.interest_rate': 'Interest Rate',
    'calculator.rental_income': 'Monthly Rental Income',
    'calculator.calculate': 'Calculate',
    'calculator.results': 'Results',
    'calculator.monthly_payment': 'Monthly Payment',
    'calculator.total_cost': 'Total Cost',
    'calculator.roi': 'Return on Investment',

    // Contact Page
    'contact.page.title': 'CONTACT',
    'contact.page.title.span': 'US',
    'contact.page.description': 'Contact our experts. We are here to help you with all your real estate needs.',
    'contact.form.title': 'SEND US A',
    'contact.form.title.span': 'MESSAGE',
    'contact.office.title': 'OFFICE',
    'contact.office.title.span': 'INFORMATION',
    'contact.social.title': 'FOLLOW',
    'contact.social.title.span': 'US',

    // Terms Page
    'terms.title': 'Terms and Conditions',
    'terms.section1.title': '1. General provisions',
    'terms.section2.title': '2. Services',
    'terms.section3.title': '3. Liability',
    'terms.section4.title': '4. Final provisions',

    // Cookies Page
    'cookies.title': 'Cookie Policy',
    'cookies.section1.title': '1. What are cookies',
    'cookies.section2.title': '2. Types of cookies we use',
    'cookies.section3.title': '3. How to manage cookies',
    'cookies.section4.title': '4. Contact information',

    // Consultation Page
    'consultation.title': 'FREE',
    'consultation.title.span': 'CONSULTATION',
    'consultation.description': 'Book a free consultation with our real estate experts. We will help you find the perfect property or develop an investment strategy.',
    'consultation.book': 'Book consultation',
    'consultation.benefits.title': 'CONSULTATION',
    'consultation.benefits.title.span': 'BENEFITS',

    // Service Detail Pages
    'service.marketing.title': 'PROPERTY',
    'service.marketing.title.span': 'MARKETING',
    'service.sellers.title': 'FOR',
    'service.sellers.title.span': 'SELLERS',
    'service.buyers.title': 'FOR',
    'service.buyers.title.span': 'BUYERS',
    'service.landlords.title': 'FOR',
    'service.landlords.title.span': 'LANDLORDS',
    'service.tenants.title': 'FOR',
    'service.tenants.title.span': 'TENANTS',
    'service.interiors.title': 'INTERIOR',
    'service.interiors.title.span': 'DESIGN',

    // Investment Search Pages
    'investment.search.title': 'INVESTMENT',
    'investment.search.title.span': 'SEARCH',
    'investment.new.title': 'NEW',
    'investment.new.title.span': 'INVESTMENTS',
    'investment.lifestyle.title': 'LIFESTYLE',
    'investment.lifestyle.title.span': 'SEARCH',

    // Main page sections
    'featured.properties.title': 'LUXURY PROPERTY',
    'featured.properties.title.span': 'OFFERS',
    'featured.properties.subtitle': 'OFFERS',
    'services.special.meeting': 'SPECIAL MEETING', 
    'services.special.meeting.subtitle': 'FOR PARTNERS INTERNATIONAL CLIENTS',
    'services.foreign.properties': 'FOREIGN',
    'services.foreign.properties.subtitle': 'PROPERTIES',
    'services.first.class': 'FIRST CLASS EXPERIENCE',
    'services.first.class.subtitle': 'TEAM DELUXE',
    'services.secret.offers': 'DISCOVER SECRET OFFERS',
    'services.secret.offers.subtitle': 'LUXURY PROPERTIES',
    'services.read_more': 'READ MORE',
    'services.see': 'SEE',
    'services.learn_more': 'LEARN MORE',

    // Property Detail Page
    'property.details.title': 'PROPERTY',
    'property.details.title.span': 'DETAILS',
    'property.gallery': 'Photo Gallery',
    'property.description': 'Description',
    'property.features': 'Features',
    'property.location.details': 'Location',
    'property.price': 'Price',
    'property.area': 'Area',
    'property.rooms': 'Rooms',
    'property.floor': 'Floor',
    'property.year': 'Year of construction',
    'property.contact_agent': 'Contact Agent',
    'property.schedule_viewing': 'Schedule Viewing',
    'property.similar': 'Similar Properties',

    // Location page districts
    'location.district.stare_miasto.name': 'Old Town',
    'location.district.stare_miasto.description': 'Heart of Krakow with historic tenements and Main Square. The most expensive and prestigious location in the city.',
    'location.district.stare_miasto.properties': '47 properties',
    'location.district.stare_miasto.highlight.1': 'Main Square',
    'location.district.stare_miasto.highlight.2': 'Cloth Hall',
    'location.district.stare_miasto.highlight.3': 'St. Mary\'s Church',
    'location.district.stare_miasto.highlight.4': 'Jagiellonian University',

    'location.district.kazimierz.name': 'Kazimierz',
    'location.district.kazimierz.description': 'Artistic district with rich Jewish history and vibrant nightlife. Cultural center of Krakow with numerous galleries and clubs.',
    'location.district.kazimierz.properties': '32 properties',
    'location.district.kazimierz.highlight.1': 'Remuh Synagogue',
    'location.district.kazimierz.highlight.2': 'Plac Nowy',
    'location.district.kazimierz.highlight.3': 'Atmospheric cafes',
    'location.district.kazimierz.highlight.4': 'Nightlife',

    'location.district.podgorze.name': 'Podgórze',
    'location.district.podgorze.description': 'Dynamically developing district with modern investments. Former industrial district transformed into modern business center.',
    'location.district.podgorze.properties': '28 properties',
    'location.district.podgorze.highlight.1': 'Schindler Museum',
    'location.district.podgorze.highlight.2': 'Bernatka Bridge',
    'location.district.podgorze.highlight.3': 'Galeria Kazimierz',
    'location.district.podgorze.highlight.4': 'Forum Przestrzenie',

    'location.district.zwierzyniec.name': 'Zwierzyniec',
    'location.district.zwierzyniec.description': 'Quiet district with lots of greenery and prestigious locations. Ideal for families who value peace and access to nature.',
    'location.district.zwierzyniec.properties': '21 properties',
    'location.district.zwierzyniec.highlight.1': 'Wolski Forest',
    'location.district.zwierzyniec.highlight.2': 'Kościuszko Mound',
    'location.district.zwierzyniec.highlight.3': 'Krakow Zoo',
    'location.district.zwierzyniec.highlight.4': 'Salvatorian Monastery',

    'location.district.zablocie.name': 'Zabłocie',
    'location.district.zablocie.description': 'Modern business district with lofts and office buildings. Center of startups and technology companies in Krakow.',
    'location.district.zablocie.properties': '35 properties',
    'location.district.zablocie.highlight.1': 'Museum of Contemporary Art',
    'location.district.zablocie.highlight.2': 'Lofts',
    'location.district.zablocie.highlight.3': 'Business Garden',
    'location.district.zablocie.highlight.4': 'Technology hub',

    'location.district.bronowice.name': 'Bronowice',
    'location.district.bronowice.description': 'Family district with single-family houses and peaceful atmosphere. Excellent communication with center and developed infrastructure.',
    'location.district.bronowice.properties': '19 properties',
    'location.district.bronowice.highlight.1': 'City parks',
    'location.district.bronowice.highlight.2': 'Primary schools',
    'location.district.bronowice.highlight.3': 'Shopping centers',
    'location.district.bronowice.highlight.4': 'Tram transport',

    'location.district.grzegorzki.name': 'Grzegórzki',
    'location.district.grzegorzki.description': 'Rapidly developing district with new residential investments. Good location with access to city center.',
    'location.district.grzegorzki.properties': '24 properties',
    'location.district.grzegorzki.highlight.1': 'New housing estates',
    'location.district.grzegorzki.highlight.2': 'Good prices',
    'location.district.grzegorzki.highlight.3': 'Close to center',
    'location.district.grzegorzki.highlight.4': 'Infrastructure development',

    'location.district.pradnik.name': 'Prądnik Czerwony',
    'location.district.pradnik.description': 'Popular residential district with good infrastructure and affordable prices. Ideal for first apartment.',
    'location.district.pradnik.properties': '31 properties',
    'location.district.pradnik.highlight.1': 'Affordable prices',
    'location.district.pradnik.highlight.2': 'Good connections',
    'location.district.pradnik.highlight.3': 'Hospitals',
    'location.district.pradnik.highlight.4': 'Shops and services',

    // Location buttons
    'location.button.see_all_attractions': 'SEE ALL ATTRACTIONS',
    'location.button.see_offers': 'SEE OFFERS',

    // Transaction page time periods  
    'transaction.time.period.30_45_days': '30-45 days',
    'transaction.time.period.14_30_days': '14-30 days',
    'transaction.time.period.45_60_days': '45-60 days',
    'transaction.time.period.60_90_days': '60-90 days',

    // Property descriptions
    'property.description.old_town': 'Luxury apartment in the heart of Krakow with views of Cloth Hall and Main Square. High ceilings, original architectural details.',
    'property.description.kazimierz': 'Exclusive penthouse in the artistic district of Krakow. Terrace with panoramic view, modern finishes.',
    'property.description.podgorze': 'Renovated tenement house with preserved historical elements. Private garden, garage, elegant interiors.',
    'property.description.zablocie': 'Modern loft in former industrial district. Industrial character, high windows, open space.',
    'property.description.zwierzyniec': 'Elegant apartment in quiet green district. Balcony with park view, parking space.',
    'property.description.bronowice': 'Luxury villa with garden and pool. Intercom, monitoring, garage for 3 cars, sauna.',
    'property.description.nowa_huta': 'Renovated apartment in well-connected location. Close to shopping center and transport.',
    'property.description.salwator': 'Unique penthouse with roof terrace. Wawel view, air conditioning, underfloor heating.',

    // Property titles
    'property.title.old_town': 'Old Town Apartment',
    'property.title.kazimierz': 'Kazimierz Penthouse',
    'property.title.podgorze': 'Podgórze Tenement',
    'property.title.zablocie': 'Zabłocie Loft',
    'property.title.zwierzyniec': 'Zwierzyniec Apartment',
    'property.title.bronowice': 'Bronowice House',
    'property.title.nowa_huta': 'Nowa Huta Apartment',
    'property.title.salwator': 'Salwator Penthouse',

    // Property locations  
    'property.location.old_town': 'Krakow, Old Town',
    'property.location.kazimierz': 'Krakow, Kazimierz',
    'property.location.podgorze': 'Krakow, Podgórze',
    'property.location.zablocie': 'Krakow, Zabłocie',
    'property.location.zwierzyniec': 'Krakow, Zwierzyniec',
    'property.location.bronowice': 'Krakow, Bronowice',
    'property.location.nowa_huta': 'Krakow, Nowa Huta',
    'property.location.salwator': 'Krakow, Salwator',

    // Search filter text
    'search.title': 'Search properties',
    'search.filters': 'Filters',
    'search.expand': 'Expand',
    'search.collapse': 'Collapse',
    'search.location.input.placeholder': 'Enter location or name...',
    'search.type.select.placeholder': 'Property type',
    'search.type.select.apartment': 'Apartment',
    'search.type.select.house': 'House',
    'search.type.select.villa': 'Villa',
    'search.type.select.penthouse': 'Penthouse',
    'search.type.select.office': 'Office',
    'search.price.from': 'Price from',
    'search.price.to': 'Price to',
    'search.rooms.select.placeholder': 'Number of rooms',
    'search.rooms.1': '1 room',
    'search.rooms.2': '2 rooms', 
    'search.rooms.3': '3 rooms',
    'search.rooms.4plus': '4+ rooms',
    'search.button': 'Search',

    // Badge translations
    'badge.premium': 'PREMIUM',
    'badge.exclusive': 'EXCLUSIVE',
    'badge.new': 'NEW',
    'badge.opportunity': 'OPPORTUNITY',
    'badge.rent': 'RENT',

    // Common UI Elements
    'ui.loading': 'Loading...',
    'ui.error': 'Error occurred',
    'ui.success': 'Success',
    'ui.cancel': 'Cancel',
    'ui.confirm': 'Confirm',
    'ui.save': 'Save',
    'ui.edit': 'Edit',
    'ui.delete': 'Delete',
    'ui.close': 'Close',
    'ui.view_more': 'View more',
    'ui.show_less': 'Show less',

    // Time and Date
    'time.days': 'days',
    'time.hours': 'hours',
    'time.minutes': 'minutes',
    'date.today': 'Today',
    'date.yesterday': 'Yesterday',
    'date.week': 'Week',
    'date.month': 'Month',
    'date.year': 'Year',
    
    // Search and filters
    'search.location.placeholder': 'Location, property type...',
    'search.price.range': 'Price Range',
    'search.price.up_to_1m': 'Up to 1,000,000 PLN',
    'search.price.1m_to_2m': '1-2 million PLN',
    'search.price.2m_to_3m': '2-3 million PLN',
    'search.price.over_3m': 'Over 3 million PLN',
    'search.property.type': 'Property Type',
    'search.property.apartment': 'Apartment',
    'search.property.house': 'House',
    'search.property.penthouse': 'Penthouse',
    'search.property.loft': 'Loft',
    'search.sort': 'Sort by',
    'search.sort.price_asc': 'Price: lowest first',
    'search.sort.price_desc': 'Price: highest first',
    'search.sort.area_asc': 'Area: smallest first',
    'search.sort.area_desc': 'Area: largest first',
    'search.found': 'Found',
    'search.properties': 'properties',
    
    // Investment search unified page
    'investment.search.unified.title': 'INVESTMENT',
    'investment.search.unified.title.span': 'SEARCH',
    'investment.search.unified.description': 'Find the perfect investment tailored to your needs, lifestyle or dream location.',
    'investment.search.unified.tab.investment': 'By Investment',
    'investment.search.unified.tab.lifestyle': 'By Lifestyle',
    'investment.search.unified.tab.location': 'By Location',

    // Investment Search Page Filters
    'investment.search.filters.title': 'Search filters',
    'investment.search.investment.name': 'Investment name',
    'investment.search.investment.name.placeholder': 'Enter name...',
    'investment.search.location': 'Location',
    'investment.search.location.placeholder': 'Select city',
    'investment.search.city.warszawa': 'Warsaw',
    'investment.search.city.krakow': 'Krakow',
    'investment.search.city.gdansk': 'Gdansk',
    'investment.search.city.wroclaw': 'Wroclaw',
    'investment.search.investment.type': 'Investment type',
    'investment.search.type.placeholder': 'Select type',
    'investment.search.type.residential': 'Residential',
    'investment.search.type.office': 'Office',
    'investment.search.type.commercial': 'Commercial',
    'investment.search.type.mixed': 'Mixed',
    'investment.search.status': 'Status',
    'investment.search.status.placeholder': 'Select status',
    'investment.search.status.sale': 'For sale',
    'investment.search.status.construction': 'Under construction',
    'investment.search.status.planning': 'In planning',
    'investment.search.status.completed': 'Completed',
    'investment.search.button': 'Search',
    'investment.search.recommended': 'Recommended investments',

    // Lifestyle Search
    'lifestyle.family.title': 'Family',
    'lifestyle.family.description': 'Perfect for families with children',
    'lifestyle.business.title': 'Business',
    'lifestyle.business.description': 'Ideal for business professionals',
    'lifestyle.active.title': 'Active',
    'lifestyle.active.description': 'For sports and fitness enthusiasts',
    'lifestyle.luxury.title': 'Luxury',
    'lifestyle.luxury.description': 'Premium and exclusive properties',
    'lifestyle.eco.title': 'Eco-friendly',
    'lifestyle.eco.description': 'Sustainable and green living',
    'lifestyle.urban.title': 'Urban',
    'lifestyle.urban.description': 'City center lifestyle',
    'lifestyle.page.title': 'Choose your lifestyle',
    'lifestyle.page.description': 'Find properties that match your way of life',
    'lifestyle.key_features': 'Key features',
    'lifestyle.properties_available': 'properties available',
    'lifestyle.view_offers': 'View offers',

    // Location Search
    'investment.location.page.title': 'Search by location',

    // Investment page - additional translations
    'button.analyze_portfolio': 'ANALYZE PORTFOLIO',
    'button.learn_more': 'LEARN MORE',
    'button.choose_portfolio': 'CHOOSE PORTFOLIO',
    'button.run_calculator': 'RUN CALCULATOR',
    'button.view_all_offers': 'VIEW ALL OFFERS',
    'button.load_more': 'LOAD MORE',
    
    // Transaction Page
    'transaction.hero.title': 'TRANSACTION',
    'transaction.hero.title.span': 'PROCESS',
    'transaction.hero.description': 'Comprehensive support for property sales and purchases in Krakow. We ensure safe and professional handling of every transaction.',
    'transaction.hero.button': 'START PROCESS',
    'transaction.process.title': 'HOW DOES THE PROCESS WORK?',
    'transaction.process.subtitle': 'Our proven process guarantees safe and effective transaction completion',
    'transaction.step1.title': 'FIRST CONSULTATION',
    'transaction.step1.description': 'We start with a detailed discussion about your needs and expectations. We analyze your budget, location preferences, and investment goals.',
    'transaction.step2.title': 'DOCUMENT ANALYSIS',
    'transaction.step2.description': 'We check all legal and financial documents related to the property. We verify legal status, encumbrances, and possible legal risks.',
    'transaction.step3.title': 'NEGOTIATIONS & SECURITY',
    'transaction.step3.description': 'We conduct professional price negotiations and transaction conditions. We secure your interests through appropriate contractual clauses.',
    'transaction.step4.title': 'TRANSACTION FINALIZATION',
    'transaction.step4.description': 'We complete the transaction with full legal and logistical support. Transfer of keys and all necessary documents.',
    'transaction.services.title': 'SERVICES INCLUDED IN',
    'transaction.services.title.span': 'TRANSACTION',
    'transaction.services.description': 'Our comprehensive services cover all aspects of real estate transactions. You don\'t need to worry about details - we\'ll handle everything.',
    'transaction.services.list.1': 'Free property valuation',
    'transaction.services.list.2': 'Comprehensive legal analysis',
    'transaction.services.list.3': 'Professional price negotiations',
    'transaction.services.list.4': 'Document preparation',
    'transaction.services.list.5': 'Full notarial service',
    'transaction.services.list.6': 'Support in obtaining credit',
    'transaction.services.list.7': 'Property insurance',
    'transaction.services.list.8': 'Transfer of keys and documents',
    'transaction.services.list.9': 'Tax consulting',
    'transaction.services.list.10': 'After-sales support',
    'transaction.services.list.11': 'Moving assistance',
    'transaction.services.list.12': 'Rental management (optional)',
    'transaction.time.title': 'TRANSACTION TIME',
    'transaction.time.subtitle': 'Average completion time',
    'transaction.time.apartment_sale': 'Apartment sale',
    'transaction.time.apartment_buy': 'Apartment purchase',
    'transaction.time.house_sale': 'House sale',
    'transaction.time.premium_investments': 'Premium investments',
    'transaction.cta.title': 'READY FOR A',
    'transaction.cta.title.span': 'TRANSACTION?',
    'transaction.cta.description': 'Contact us today and start a safe process of selling or buying real estate',
    
    // Location Page
    'location.hero.title': 'LOCATIONS IN',
    'location.hero.title.span': 'KRAKOW',
    'location.hero.description': 'Discover the best districts of Krakow. Each offers a unique character and diverse investment opportunities.',
    'location.amenities.title': 'WHY',
    'location.amenities.title.span': 'KRAKOW?',
    'location.amenities.description': 'Krakow is a city with exceptional quality of life, combining history with modernity',
    'location.amenities.transport': 'Transport',
    'location.amenities.cafes': 'Cafés',
    'location.amenities.restaurants': 'Restaurants',
    'location.amenities.culture': 'Culture',
    'location.districts.title': 'POPULAR',
    'location.districts.title.span': 'DISTRICTS',
    'location.districts.description': 'Check our offer in the most popular districts of Krakow',
    'location.districts.attractions': 'Main attractions:',
    'location.investment.title': 'INVESTMENT',
    'location.investment.title.span': 'POTENTIAL',
    'location.investment.description': 'Krakow is one of the most dynamically developing real estate markets in Poland. The city offers excellent prospects for long-term investors.',
    'location.investment.growth': 'Year-over-year price growth',
    'location.investment.yield': 'Rental yield',
    'location.investment.demand': 'Rental demand',
    'location.investment.demand.high': 'Very high',
    'location.investment.residents': 'Residents',
    'location.investment.students': 'Students',
    'location.investment.tourists': 'Tourists annually',
    'location.investment.companies': 'International companies',
    
    // Investment Page
    'investment.hero.title': 'REAL ESTATE',
    'investment.hero.title.span': 'INVESTMENTS',
    'investment.hero.description': 'Professional investment consulting in real estate. Build your wealth with Partners International.',
    'investment.types.title': 'INVESTMENT',
    'investment.types.title.span': 'TYPES',
    'investment.types.description': 'Diverse investment opportunities tailored to your financial goals',
    'investment.portfolios.title': 'SUGGESTED',
    'investment.portfolios.title.span': 'PORTFOLIOS',
    'investment.portfolios.description': 'Sample capital allocations depending on investor risk profile',
    'investment.calculator.title': 'INVESTMENT',
    'investment.calculator.title.span': 'CALCULATOR',
    'investment.calculator.description': 'Check the potential return on your real estate investment. Our tool takes into account all key market factors.',
    'investment.start': 'START YOUR',
    'investment.start.adventure': 'INVESTMENT ADVENTURE',

    // Investment Search translations
    'investment.search.hero.title': 'Find Your Perfect',
    'investment.search.hero.title.span': 'Investment',
    'investment.search.hero.description': 'Discover the best investment opportunities in Poland. Professional consulting and comprehensive service.',
    'investment.search.hero.button': 'Start Search',

    // Investment New translations
    'investment.new.page.title': 'New Investments',
    'investment.new.page.description': 'Discover the latest investment projects in the premium real estate market',
    'investment.new.stats.new': 'New investments',
    'investment.new.stats.luxury': 'Luxury projects',
    'investment.new.stats.cities': 'Cities',
    'investment.new.stats.avg_price': 'Average price PLN',
    'investment.new.categories.all': 'All',
    'investment.new.categories.luxury': 'Luxury',
    'investment.new.categories.eco': 'Eco-friendly',
    'investment.new.categories.office': 'Office',
    'investment.new.badge.new': 'NEW',
    'investment.new.price_from': 'From',
    'investment.new.key_features': 'Key Features',
    'investment.new.view_details': 'View Details',
    'investment.new.register': 'Register',
    'investment.new.cta.title': 'Stay updated with new investments',
    'investment.new.cta.description': 'Be the first to know about the latest projects',
    'investment.new.cta.button': 'Subscribe to newsletter',

    // Investment features
    'investment.features.taras_widokowy': 'Scenic Terrace',
    'investment.features.concierge': 'Concierge 24/7',
    'investment.features.spa': 'SPA',
    'investment.features.parking_podziemny': 'Underground Parking',
    'investment.features.panele_sloneczne': 'Solar Panels',
    'investment.features.zielen_pionowa': 'Vertical Gardens',
    'investment.features.ladowarki_ev': 'EV Chargers',
    'investment.features.ogrody_spoleczne': 'Community Gardens',
    'investment.features.smart_building': 'Smart Building',
    'investment.features.konferencyjne': 'Conference Rooms',
    'investment.features.fitness': 'Fitness Center',
    'investment.features.restauracja': 'Restaurant',

    // Dates
    'investment.dates.january': 'January',
    'investment.dates.february': 'February',
    'investment.dates.march': 'March',
    'investment.dates.april': 'April',
    'investment.dates.may': 'May',
    'investment.dates.june': 'June',

    // Categories detailed
    'investment.categories.luxury.title': 'Luxury Investments',
    'investment.categories.luxury.description': 'Filtered results for luxury category',
    'investment.categories.eco.title': 'Eco-friendly Investments',
    'investment.categories.eco.description': 'Filtered results for eco-friendly category',
    'investment.categories.office.title': 'Office Investments',
    'investment.categories.office.description': 'Filtered results for office category',
    
    // Services Page
    'services.hero.title': 'OUR',
    'services.hero.title.span': 'SERVICES',
    'services.hero.description': 'Comprehensive real estate services in Krakow. From valuation to management - everything in one place.',
    'services.main.title': 'MAIN',
    'services.main.title.span': 'SERVICES',
    'services.main.description': 'Professional real estate services tailored to your needs',
    'services.additional.title': 'ADDITIONAL',
    'services.additional.title.span': 'SERVICES',
    'services.additional.description': 'Expand your possibilities with our specialized services',
    'services.process.title': 'HOW WE',
    'services.process.title.span': 'WORK?',
    'services.process.description': 'Our proven process guarantees the highest quality of service',
    'services.support.title': 'SUPPORT',
    'services.support.title.span': '24/7',
    'services.support.description': 'Our team of experts is available 24/7. You will receive professional support at every stage of cooperation.',
    
    // Common Lorem
    'lorem.short': 'Premium properties in the finest locations. Professional consulting and comprehensive service.',
    'lorem.medium': 'We specialize in selling exclusive properties in Poland and abroad. Our team of experts provides professional consulting at every stage of the transaction, ensuring the highest level of service.',
    'lorem.long': 'Partners International is a leading company in the luxury real estate market. For over a decade, we have been helping clients realize their dreams of the perfect apartment or house. Our portfolio includes the most valuable properties in prestigious locations throughout Poland.',
    
    // Navigation - Additional Menu Items
    'nav.investments': 'INVESTMENTS',
    'nav.about': 'ABOUT AGENCY',
    'nav.investments.search': 'Search by investment',
    'nav.investments.new': 'New investments',
    'nav.investments.lifestyle': 'Search by lifestyle',
    'nav.investments.location': 'Search by location',
    'nav.services.marketing': 'Property marketing',
    'nav.services.sellers': 'For sellers',
    'nav.services.buyers': 'For buyers',
    'nav.services.landlords': 'For landlords',
    'nav.services.tenants': 'For tenants',
    'nav.services.interiors': 'Interior design',
    'nav.about.us': 'ABOUT US',
    'nav.about.team': 'TEAM',
    'nav.about.blog': 'BLOG',
    'nav.about.career': 'CAREER',
    'nav.about.office': 'OUR OFFICE',
    'nav.about.media': 'IN MEDIA',
    
    // About Us Page
    'about.hero.title': 'ABOUT',
    'about.hero.title.span': 'US',
    'about.hero.description': 'Premium Partners International is more than a real estate agency. It is a team of enthusiasts who have been helping clients realize their dreams of the perfect home for over a decade. Our story is one of continuous pursuit of excellence and building lasting relationships.',
    'about.mission.title': 'OUR',
    'about.mission.title.span': 'MISSION',
    'about.mission.description.1': 'We believe that everyone deserves an exceptional home. Our mission is to connect people with properties that not only meet their needs but exceed expectations. We specialize in the premium segment, where every detail matters.',
    'about.mission.description.2': 'Over the years, we have built a reputation based on trust, professionalism and individual approach to each client. Our market knowledge, combined with modern technologies, allows us to offer the highest quality services.',
    'about.achievements.title': 'OUR',
    'about.achievements.title.span': 'ACHIEVEMENTS',
    'about.achievements.description': 'Numbers that speak for themselves about our experience and success',
    'about.achievement.transactions': 'Completed transactions',
    'about.achievement.transactions.desc': 'We helped over 500 clients find their dream apartments',
    'about.achievement.value': 'Value of sold properties',
    'about.achievement.value.desc': 'PLN in luxury properties sold by our team',
    'about.achievement.satisfaction': 'Satisfied customers',
    'about.achievement.satisfaction.desc': 'Our clients recommend us to friends and family',
    'about.achievement.awards': 'Industry awards',
    'about.achievement.awards.desc': 'Recognized by experts for quality of service',
    'about.history.title': 'OUR',
    'about.history.title.span': 'HISTORY',
    'about.history.description': 'Journey from beginnings to premium real estate market leader',
    'about.values.title': 'WHAT MAKES US',
    'about.values.title.span': 'UNIQUE',
    'about.values.individual.title': 'Individual approach',
    'about.values.individual.desc': 'Every client is unique to us. We tailor our services to specific needs and expectations.',
    'about.values.portfolio.title': 'Exclusive portfolio',
    'about.values.portfolio.desc': 'We offer the best premium properties in the most beautiful locations in Krakow and surroundings.',
    'about.values.international.title': 'International reach',
    'about.values.international.desc': 'We work with clients from around the world, offering services in multiple languages.',
    
    // Privacy Policy Page
    'privacy.title': 'Privacy Policy',
    'privacy.section1.title': '1. General information',
    'privacy.section2.title': '2. Personal data processing',
    'privacy.section3.title': '3. Cookies and tracking technologies',
    'privacy.section4.title': '4. User rights',
    'privacy.section5.title': '5. Contact',
    
    // For Landlords Page
    'landlords.hero.title': 'For Landlords',
    'landlords.hero.description': 'Professional rental property management. We will find reliable tenants and ensure hassle-free rental.',
    'landlords.benefits.title': 'Why trust us?',
    'landlords.services.tab': 'Our Services',
    'landlords.packages.tab': 'Packages',
    'landlords.process.tab': 'Process',
    'landlords.service.finding.title': 'Finding tenants',
    'landlords.service.finding.description': 'Quick finding of reliable tenants',
    'landlords.service.management.title': 'Rental management',
    'landlords.service.management.description': 'Comprehensive rental service',
    'landlords.service.legal.title': 'Legal service',
    'landlords.service.legal.description': 'Legal security of rental',
    'landlords.service.optimization.title': 'Profit optimization',
    'landlords.service.optimization.description': 'Maximizing rental income',
    'landlords.package.basic.name': 'Tenant finding only',
    'landlords.package.basic.price': 'One-time 50% of monthly rent',
    'landlords.package.basic.description': 'We will find and verify tenant',
    'landlords.package.full.name': 'Full management',
    'landlords.package.full.price': '8% of monthly rent',
    'landlords.package.full.description': 'Comprehensive rental service',
    'landlords.package.premium.name': 'Premium management',
    'landlords.package.premium.price': '12% of monthly rent',
    'landlords.package.premium.description': 'Highest level of service',
    'landlords.cta.title': 'Rent your property with experts',
    'landlords.cta.description': 'Contact us and see how we can help you rent your property hassle-free with guarantee of best tenants.',
    
    // For Sellers Page
    'sellers.hero.title': 'For Sellers',
    'sellers.hero.description': 'Professional property sales service. We will help you sell your property at the best price in the shortest possible time.',
    
    // For Buyers Page
    'buyers.hero.title': 'For Buyers',
    'buyers.hero.description': 'We will help you find and buy the perfect property tailored to your needs, budget and lifestyle.',
    
    // For Tenants Page
    'tenants.hero.title': 'For Tenants',
    'tenants.hero.description': 'Professional rental assistance. We will help you find the perfect apartment or house for rent.',
    
    // Marketing Service Page
    'marketing.hero.title': 'Marketing Services',
    'marketing.hero.description': 'Professional real estate marketing that sells. We create campaigns that attract the right buyers.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('pl');
  
  const t = (key: string): string => {
    console.log(`[LanguageProvider] Translating key: ${key}, current language: ${language}`);
    const result = translations[language][key as keyof typeof translations[typeof language]] || key;
    if (result === key) {
      console.warn(`[LanguageProvider] Missing translation for key: ${key} in language: ${language}`);
    }
    return result;
  };

  const changeLanguage = (lang: Language) => {
    console.log(`[LanguageProvider] Changing language from ${language} to ${lang}`);
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};